### ISSUE TITLE
Be more descriptive about multiple colons

### ISSUE THREAD

**Issue by parkr** [dtao/safe_yaml#54]
Jekyll uses SafeYAML to parse all YAML we read in from a user's filesystem. We use it for titles, for dates – for every piece of metadata about a post or page we can. As such, we rely heavily on SafeYAML's behaviour regarding well-formed and malformed YAML.

I received an issue today by the fantastic @gjtorikian who mentioned that a friend of his had difficulty when a value he wrote contained a colon itself, thus causing what should be a `String` value to become a `Hash`. This caused strange behaviour ( https://github.com/jekyll/jekyll/issues/2030 ) and lots of confusion.

Is there a way we can check for colons on non-newline separated lines, such that:

```ruby
> SafeYAML.load("---\ndescription: we're working with great developers at: large, small, medium, massive, miniscule, and made-out-of-jam companies")
#=> {"description" => "we're working with great developers at: large, small, medium, massive, miniscule, and made-out-of-jam companies"}
> SafeYAML.load("---\ndescription: we're working with great developers\nat: lots of places")
#=> {"description" => "we're working with great developers", "at" => "lots of places"}
```

The newline before the term that ends with the `:` signifies that it's a new key.

**Comment by dottorblaster** [comment]
Upvote for this.
