### ISSUE TITLE
Ruby 2.2.0 - undefined method `tagged_classes' for Psych:Module (NoMethodError)

### ISSUE THREAD

**Issue by ethicalhack3r** [dtao/safe_yaml#73]
```
$ ruby -v
ruby 2.2.0preview1 (2014-09-17 trunk 47616) [x86_64-darwin14]
```

Getting the following error with Ruby 2.2.0 when running WPScan's specs:
```
$ rspec
/Users/ryan/.rvm/gems/ruby-2.2.0-preview1/gems/safe_yaml-1.0.3/lib/safe_yaml/load.rb:43:in `<module:SafeYAML>': undefined method `tagged_classes' for Psych:Module (NoMethodError)
```

We're tracking it here: https://github.com/wpscanteam/wpscan/issues/748

**Comment by parkr** [comment]
Can you upgrade to 2.2.0 (not preview) and try again?

**Comment by ethicalhack3r** [comment]
I hadn't realised I was using the preview version. A friend used version 2.2.0 (not preview) and didn't have any issues. I'm currently in dependency hell trying to get 2.2.0 (not preview) installed. Will let you know when I do but I'm confident this is due to the preview version, feel free to close.

**Comment by ethicalhack3r** [comment]
Updating to real Ruby 2.2.0 and safe_yaml version 1.0.4 fixed it

**Comment by dantesolis** [comment]
Upgrading to `safe_yaml`, '~> 1.0.4'` solved my problem
